import type { City } from "../types";

export const cities: City[] = [
  {
    slug: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    lat: 12.9716,
    lng: 77.5946,
    servedStoreSlugs: [
      "bengaluru-yeswanthpur",
      "bengaluru-kalyan-nagar",
      "bengaluru-yelahanka",
      "bengaluru-cv-raman-nagar",
      "bengaluru-jp-nagar",
    ],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 103,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["hyderabad", "chennai"],
    localFaqIds: ["bengaluru-rto", "bengaluru-charging"],
    testimonialIds: ["t-priya-chennai", "t-arvind-bengaluru"],
    introCopy:
      "Bengaluru's stop-and-go traffic was made for electric scooters — predictable distances, short trips, and enough charging time at home. ElectricPe operates five Mobility Centers across the city, from Yeswanthpur to JP Nagar, each staffed with trained technicians who'll walk you through every detail before you buy. No licence required for any scooter in our lineup.",
    customerCount: "3,200+",
    scootersSoldCount: "1,100+",
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    lat: 28.6139,
    lng: 77.209,
    servedStoreSlugs: ["delhi-nehru-place"],
    bestsellerScooterVariantSlugs: ["4all-lithium-ion", "xypro-lithium-ion"],
    localFuelPricePerLitre: 97,
    localElectricityRatePerKwh: 8,
    nearbyCitySlugs: ["gurugram"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Delhi's air-quality imperatives make the switch to electric a public-health choice, not just a financial one. With a fully paid delivery fleet using our scooters and rising residential adoption, ElectricPe brings its service-first ownership model to the capital.",
    customerCount: "800+",
    scootersSoldCount: "280+",
  },
  {
    slug: "gurugram",
    name: "Gurugram",
    state: "Haryana",
    lat: 28.4595,
    lng: 77.0266,
    servedStoreSlugs: ["gurugram-sector-14"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 97,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["delhi"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Gurugram's corporate campuses and gated communities are perfect for the ElectricPe ownership model — predictable commutes, dedicated parking, and accessible charging. Our Sector 14 Mobility Center offers doorstep test rides across all NCR sectors.",
    customerCount: "620+",
    scootersSoldCount: "210+",
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    lat: 26.9124,
    lng: 75.7873,
    servedStoreSlugs: ["jaipur-malviya-nagar"],
    bestsellerScooterVariantSlugs: ["ep-city-plus", "xypro-lithium-ion"],
    localFuelPricePerLitre: 108,
    localElectricityRatePerKwh: 7,
    nearbyCitySlugs: [],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Jaipur riders have been some of the earliest ElectricPe adopters in Rajasthan — the combination of low top-speed legal advantages, minimal running cost, and doorstep service has resonated here. Visit our Malviya Nagar Mobility Center for a test ride.",
    customerCount: "450+",
    scootersSoldCount: "160+",
  },
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    lat: 17.385,
    lng: 78.4867,
    servedStoreSlugs: ["hyderabad-madhapur"],
    bestsellerScooterVariantSlugs: ["jett-lithium-ion", "xypro-lithium-ion"],
    localFuelPricePerLitre: 109,
    localElectricityRatePerKwh: 7.5,
    nearbyCitySlugs: ["bengaluru"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Hyderabad's fast-growing IT corridor and wide arterial roads make the Jett our top seller here — the 12-inch wheels and longer seat suit the longer commutes from Madhapur and Gachibowli.",
    customerCount: "540+",
    scootersSoldCount: "180+",
  },
  {
    slug: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    lat: 13.0827,
    lng: 80.2707,
    servedStoreSlugs: ["chennai-anna-nagar"],
    bestsellerScooterVariantSlugs: ["ep-city-plus", "xypro-lithium-ion"],
    localFuelPricePerLitre: 102,
    localElectricityRatePerKwh: 6.5,
    nearbyCitySlugs: ["bengaluru"],
    localFaqIds: [],
    testimonialIds: ["t-priya-chennai", "t-kiran-chennai"],
    introCopy:
      "Chennai's delivery-led commerce economy has driven EP City Plus adoption — last-mile partners love the low total cost of ownership. ElectricPe's Anna Nagar Mobility Center offers same-day service for fleet operators.",
    customerCount: "510+",
    scootersSoldCount: "170+",
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    lat: 19.076,
    lng: 72.8777,
    servedStoreSlugs: ["mumbai-andheri"],
    bestsellerScooterVariantSlugs: ["jett-lithium-ion", "xypro-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 9,
    nearbyCitySlugs: ["pune"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Mumbai's narrow lanes and heavy parking constraints favour low-footprint electric scooters. Our Andheri Mobility Center serves Western line suburbs with doorstep test rides and at-home charging installation.",
    customerCount: "380+",
    scootersSoldCount: "120+",
  },
  {
    slug: "pune",
    name: "Pune",
    state: "Maharashtra",
    lat: 18.5204,
    lng: 73.8567,
    servedStoreSlugs: ["pune-kothrud"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "jett-lithium-ion"],
    localFuelPricePerLitre: 104,
    localElectricityRatePerKwh: 8.5,
    nearbyCitySlugs: ["mumbai"],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Pune's student population and IT workforce make it a natural fit for ElectricPe. Kothrud Mobility Center offers extended weekend test-ride hours for first-time buyers.",
    customerCount: "310+",
    scootersSoldCount: "100+",
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    lat: 23.0225,
    lng: 72.5714,
    servedStoreSlugs: ["ahmedabad-bodakdev"],
    bestsellerScooterVariantSlugs: ["4all-lithium-ion", "xypro-lithium-ion"],
    localFuelPricePerLitre: 96,
    localElectricityRatePerKwh: 7,
    nearbyCitySlugs: [],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Ahmedabad's generous charging infrastructure and subsidy-friendly EV policy make our Bodakdev Mobility Center one of the fastest-growing in the network.",
    customerCount: "290+",
    scootersSoldCount: "95+",
  },
  {
    slug: "chandigarh",
    name: "Chandigarh",
    state: "Chandigarh",
    lat: 30.7333,
    lng: 76.7794,
    servedStoreSlugs: ["chandigarh-sector-17"],
    bestsellerScooterVariantSlugs: ["xypro-lithium-ion", "4all-lithium-ion"],
    localFuelPricePerLitre: 96,
    localElectricityRatePerKwh: 7,
    nearbyCitySlugs: [],
    localFaqIds: [],
    testimonialIds: [],
    introCopy:
      "Chandigarh's planned streets and cycle-friendly infrastructure make it an EV-natural city. Our Sector 17 Mobility Center runs test rides seven days a week.",
    customerCount: "200+",
    scootersSoldCount: "70+",
  },
];

export const getCity = (slug: string): City | undefined =>
  cities.find((c) => c.slug === slug);

export const allCitySlugs = cities.map((c) => c.slug);
