import type { Scooter } from "../types";

export const scooters: Scooter[] = [
  {
    brand: "xypro",
    variantSlug: "lithium-ion",
    name: "Xypro Lithium Ion",
    tagline: "Long range for city commutes — lithium efficiency, lead-acid pricing",
    priceOnRoad: 64999,
    priceOriginal: 67999,
    emiFrom: 2199,
    specs: {
      rangeKm: 100,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 82,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years / 30,000 km",
    },
    colors: [
      {
        name: "Cherry Red",
        hex: "#C62828",
        gallery: ["/img/xypro_brand_banner.webp"],
      },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "100 km real-world range on a single charge",
      "Charges in 4 hours on any regular 5A socket",
      "Digital speedometer with remaining-range estimate",
      "Anti-theft alarm + remote-lock key fob",
      "USB charging port + detachable lithium battery",
    ],
    useCases: ["commute", "student", "family"],
    licenseRequired: false,
    faqIds: ["xypro-range", "xypro-charging", "xypro-warranty"],
    testimonialIds: ["t-priya-chennai", "t-arvind-bengaluru"],
    availabilityCities: [
      "bengaluru",
      "hyderabad",
      "chennai",
      "delhi",
      "gurugram",
      "jaipur",
      "mumbai",
      "pune",
    ],
    seo: {
      title: "Xypro Lithium Ion — 100 km Range Electric Scooter | ElectricPe",
      description:
        "Xypro Lithium Ion electric scooter. 100 km range, 25 km/h top speed, 4h charge, 3-year warranty. No licence required. EMI from ₹2,199/month. Book a free test ride.",
    },
  },
  {
    brand: "xypro",
    variantSlug: "lead-acid",
    name: "Xypro Lead Acid",
    tagline: "Budget-friendly daily rider — trusted chemistry, proven parts",
    priceOnRoad: 53999,
    priceOriginal: 56999,
    emiFrom: 1799,
    specs: {
      rangeKm: 60,
      topSpeedKmh: 25,
      chargeTimeHours: 8,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 96,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years motor / 12 months battery",
    },
    colors: [
      { name: "Pearl White", hex: "#F5F5F5", gallery: ["/img/xypro_brand_banner.webp"] },
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/xypro_brand_banner.webp"] },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "60 km real-world range on a single charge",
      "Lowest upfront price in the ElectricPe range",
      "Replaceable lead-acid battery — easy roadside swap",
      "Digital speedometer, anti-theft alarm",
      "Service & parts at any ElectricPe Mobility Center",
    ],
    useCases: ["commute", "student", "family"],
    licenseRequired: false,
    faqIds: ["xypro-range", "xypro-battery-life"],
    testimonialIds: ["t-rajesh-bengaluru"],
    availabilityCities: [
      "bengaluru",
      "hyderabad",
      "chennai",
      "delhi",
      "gurugram",
      "jaipur",
    ],
    seo: {
      title: "Xypro Lead Acid — Affordable 60km EV Scooter | ElectricPe",
      description:
        "Xypro Lead Acid electric scooter. 60 km range, 25 km/h top speed, 3-year motor warranty. No licence required. EMI from ₹1,799/month. Book a free test ride.",
    },
  },
  {
    brand: "jett",
    variantSlug: "lithium-ion",
    name: "Jett Lithium Ion",
    tagline: "Elegant, spacious, built for the family — daily rides with cargo comfort",
    priceOnRoad: 73000,
    emiFrom: 2499,
    specs: {
      rangeKm: 90,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 88,
      payloadKg: 160,
      wheelSize: "12 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years / 30,000 km",
    },
    colors: [
      { name: "Crimson", hex: "#B71C1C", gallery: ["/img/jett_brand_banner.webp"] },
    ],
    heroGallery: ["/img/jett_brand_banner.webp"],
    featureBullets: [
      "90 km range — enough for two daily commutes + errands",
      "Cushioned dual-seat with lumbar support",
      "Large under-seat storage (10 kg luggage capacity)",
      "12-inch wheels for smoother Indian roads",
      "Detachable lithium battery — charge at home or desk",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["jett-storage", "jett-comfort"],
    testimonialIds: ["t-shalini-coimbatore"],
    availabilityCities: ["bengaluru", "chennai", "hyderabad", "delhi", "gurugram"],
    seo: {
      title: "Jett Lithium Ion — 90km Family Electric Scooter | ElectricPe",
      description:
        "Jett Lithium Ion electric scooter with 12-inch wheels, 10kg storage, 90 km range. Built for family rides. 3-year warranty. EMI from ₹2,499/month.",
    },
  },
  {
    brand: "jett",
    variantSlug: "lead-acid",
    name: "Jett Lead Acid",
    tagline: "Same elegance, lighter on the wallet — proven battery chemistry",
    priceOnRoad: 64999,
    emiFrom: 2199,
    specs: {
      rangeKm: 60,
      topSpeedKmh: 25,
      chargeTimeHours: 8,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 102,
      payloadKg: 160,
      wheelSize: "12 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years motor / 12 months battery",
    },
    colors: [
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/jett_brand_banner.webp"] },
    ],
    heroGallery: ["/img/jett_brand_banner.webp"],
    featureBullets: [
      "60 km range for predictable daily use",
      "Same seat + storage + wheels as the lithium Jett",
      "Replaceable battery — easy to service anywhere",
      "Starting at ₹64,999 on-road",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["jett-comfort"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "chennai", "hyderabad", "delhi", "gurugram"],
    seo: {
      title: "Jett Lead Acid — Affordable Family EV Scooter | ElectricPe",
      description:
        "Jett Lead Acid electric scooter. 60 km range, 12-inch wheels, 10kg storage. 3-year motor warranty. EMI from ₹2,199/month.",
    },
  },
  {
    brand: "ep",
    variantSlug: "city-plus",
    name: "EP City Plus",
    tagline: "Most affordable ElectricPe — for first-time riders and tight budgets",
    priceOnRoad: 43000,
    emiFrom: 1499,
    specs: {
      rangeKm: 60,
      topSpeedKmh: 25,
      chargeTimeHours: 8,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.2,
      motorWattage: 250,
      weightKg: 78,
      payloadKg: 130,
      wheelSize: "10 inch",
      brakes: "Front drum, rear drum",
      suspension: "Telescopic front, mono rear",
      certification: "ARAI approved",
      warranty: "3 years motor / 12 months battery",
    },
    colors: [
      { name: "Signal Red", hex: "#D14343", gallery: ["/img/ep_brand_banner.webp"] },
    ],
    heroGallery: ["/img/ep_brand_banner.webp"],
    featureBullets: [
      "Lowest price in the ElectricPe range — ₹43,000 on-road",
      "60 km range — covers the typical Indian delivery day",
      "Lightweight, easy to park in narrow lanes",
      "Perfect for delivery partners and first-time riders",
    ],
    useCases: ["delivery", "student"],
    licenseRequired: false,
    faqIds: ["ep-delivery", "ep-battery-life"],
    testimonialIds: ["t-kiran-chennai"],
    availabilityCities: ["bengaluru", "chennai", "hyderabad", "mumbai", "pune"],
    seo: {
      title: "EP City Plus — Most Affordable EV Scooter ₹43,000 | ElectricPe",
      description:
        "EP City Plus — ElectricPe's most affordable electric scooter at ₹43,000. 60 km range, 3-year motor warranty. No licence required. EMI from ₹1,499/month.",
    },
  },
  {
    brand: "4all",
    variantSlug: "lithium-ion",
    name: "4ALL Lithium Ion",
    tagline: "Best range, zero hassle — no registration, no licence, no stress",
    priceOnRoad: 75000,
    emiFrom: 2599,
    specs: {
      rangeKm: 95,
      topSpeedKmh: 25,
      chargeTimeHours: 4,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.8,
      motorWattage: 250,
      weightKg: 85,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years / 30,000 km",
    },
    colors: [
      { name: "Cloud White", hex: "#FAFAFA", gallery: ["/img/4all_brand_banner.webp"] },
    ],
    heroGallery: ["/img/4all_brand_banner.webp"],
    featureBullets: [
      "95 km real-world range on a single charge",
      "No licence, no registration — ride it home the same day",
      "Detachable battery — charge indoors in 4 hours",
      "LED headlamp + digital console",
    ],
    useCases: ["commute", "family", "student"],
    licenseRequired: false,
    faqIds: ["4all-licence", "4all-range"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "hyderabad", "delhi", "gurugram", "jaipur"],
    seo: {
      title: "4ALL Lithium Ion — 95km No-Licence EV Scooter | ElectricPe",
      description:
        "4ALL Lithium Ion electric scooter. 95 km range, no licence, no registration. 3-year warranty. EMI from ₹2,599/month. Book a free test ride.",
    },
  },
  {
    brand: "4all",
    variantSlug: "lead-acid",
    name: "4ALL Lead Acid",
    tagline: "Hassle-free ownership with classic lead-acid reliability",
    priceOnRoad: 62000,
    emiFrom: 2099,
    specs: {
      rangeKm: 95,
      topSpeedKmh: 25,
      chargeTimeHours: 8,
      batteryType: "lead-acid",
      batteryCapacityKwh: 1.44,
      motorWattage: 250,
      weightKg: 98,
      payloadKg: 150,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years motor / 12 months battery",
    },
    colors: [
      { name: "Cloud White", hex: "#FAFAFA", gallery: ["/img/4all_brand_banner.webp"] },
    ],
    heroGallery: ["/img/4all_brand_banner.webp"],
    featureBullets: [
      "95 km range — best range in its price bracket",
      "No licence, no registration required",
      "Proven lead-acid chemistry, serviceable anywhere",
    ],
    useCases: ["commute", "family"],
    licenseRequired: false,
    faqIds: ["4all-licence"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "hyderabad", "delhi", "gurugram", "jaipur"],
    seo: {
      title: "4ALL Lead Acid — 95km Affordable EV Scooter | ElectricPe",
      description:
        "4ALL Lead Acid electric scooter. 95 km range, no licence required. 3-year motor warranty. EMI from ₹2,099/month.",
    },
  },
  {
    brand: "xypro",
    variantSlug: "swap",
    name: "Xypro Swap",
    tagline: "Own the scooter, subscribe the battery — lowest upfront cost",
    priceOnRoad: 35000,
    emiFrom: 1299,
    specs: {
      rangeKm: 60,
      topSpeedKmh: 25,
      chargeTimeHours: 0,
      batteryType: "lithium-ion",
      batteryCapacityKwh: 1.6,
      motorWattage: 250,
      weightKg: 75,
      payloadKg: 140,
      wheelSize: "10 inch",
      brakes: "Front disc, rear drum",
      suspension: "Telescopic front, dual rear",
      certification: "ARAI approved",
      warranty: "3 years vehicle / battery subscription",
    },
    colors: [
      { name: "Matte Black", hex: "#1D2939", gallery: ["/img/xypro_brand_banner.webp"] },
    ],
    heroGallery: ["/img/xypro_brand_banner.webp"],
    featureBullets: [
      "Lowest sticker price — ₹35,000 on-road",
      "Battery-as-a-service: swap at any partner station in seconds",
      "Ideal for delivery riders who can't afford charging downtime",
      "No charging at home — no electricity bill spike",
    ],
    useCases: ["delivery"],
    licenseRequired: false,
    faqIds: ["xypro-swap-subscription"],
    testimonialIds: [],
    availabilityCities: ["bengaluru", "hyderabad", "delhi"],
    seo: {
      title: "Xypro Swap — Battery Swap EV Scooter ₹35,000 | ElectricPe",
      description:
        "Xypro Swap electric scooter with battery-as-a-service. Lowest upfront cost at ₹35,000. Perfect for delivery partners. No charging downtime.",
    },
  },
];

export const scootersByBrand = scooters.reduce<Record<string, Scooter[]>>(
  (acc, s) => {
    (acc[s.brand] ??= []).push(s);
    return acc;
  },
  {},
);

export const getScooter = (
  brand: string,
  variantSlug: string,
): Scooter | undefined =>
  scooters.find((s) => s.brand === brand && s.variantSlug === variantSlug);

export const getBrandFlagship = (brand: string): Scooter | undefined =>
  scooters.find((s) => s.brand === brand && s.variantSlug === "lithium-ion") ??
  scooters.find((s) => s.brand === brand);
