import type { Charger } from "../types";

export const chargers: Charger[] = [
  {
    slug: "oakter-3-3kw",
    brand: "oakter",
    name: "ElectricPe Oakter 3.3 kW",
    image: "/img/chargers/oakter.webp",
    gallery: ["/img/chargers/oakter.webp"],
    powerKw: 3.3,
    currentType: "AC",
    connectorType: "Bharat AC-001",
    ocppCompatible: false,
    smart: false,
    recommendedForBrands: ["xypro", "jett", "4all"],
    priceInr: 4999,
    installationIncluded: true,
    specs: {
      Input: "230 VAC, 15A",
      Output: "3.3 kW AC",
      Cable: "5 m",
      Protection: "IP54",
      Warranty: "1 year",
    },
    faqIds: [],
    seo: {
      title: "Oakter 3.3 kW Home EV Charger | ₹4,999 | ElectricPe",
      description:
        "Oakter 3.3 kW home EV charger with installation included. Compatible with every ElectricPe scooter. Bharat AC-001 standard. 1-year warranty.",
    },
  },
  {
    slug: "riod-powerpod-7-4kw",
    brand: "riod",
    name: "RIOD Powerpod 7.4 kW",
    image: "/img/chargers/riod-74.webp",
    gallery: ["/img/chargers/riod-74.webp"],
    powerKw: 7.4,
    currentType: "AC",
    connectorType: "Type-2",
    ocppCompatible: true,
    smart: true,
    recommendedForBrands: ["xypro", "jett", "4all"],
    priceInr: 38200,
    installationIncluded: true,
    specs: {
      Input: "230 VAC, 32A",
      Output: "7.4 kW AC",
      Connector: "IEC 62196 Type-2",
      Cable: "5 m",
      Protocol: "OCPP 1.6J",
      Connectivity: "Wi-Fi + Ethernet",
      Warranty: "3 years",
    },
    faqIds: [],
    seo: {
      title: "RIOD Powerpod 7.4 kW EV Charger | ElectricPe",
      description:
        "RIOD Powerpod 7.4 kW smart Type-2 EV charger with OCPP 1.6J, Wi-Fi, and installation included. Manufacturer warranty included.",
    },
  },
  {
    slug: "teltonika-teltocharge-7-4kw",
    brand: "teltonika",
    name: "Teltonika TeltoCharge 7.4 kW",
    image: "/img/chargers/teltonika-74.webp",
    gallery: ["/img/chargers/teltonika-74.webp"],
    powerKw: 7.4,
    currentType: "AC",
    connectorType: "Type-2",
    ocppCompatible: true,
    smart: true,
    recommendedForBrands: ["xypro", "jett", "4all"],
    priceInr: 56175,
    installationIncluded: true,
    specs: {
      Input: "230 VAC, 32A",
      Output: "7.4 kW AC",
      Connector: "IEC 62196 Type-2",
      Protocol: "OCPP 1.6J / 2.0.1",
      Connectivity: "Wi-Fi, Ethernet, 4G optional",
      Warranty: "3 years",
    },
    faqIds: [],
    seo: {
      title: "Teltonika TeltoCharge 7.4 kW EV Charger | ElectricPe",
      description:
        "Teltonika TeltoCharge 7.4 kW smart charger with OCPP 2.0.1 support. Commercial-grade Type-2 charging for residential and business installs.",
    },
  },
  {
    slug: "riod-powerpod-22kw",
    brand: "riod",
    name: "RIOD Powerpod 22 kW",
    image: "/img/chargers/riod-22.webp",
    gallery: ["/img/chargers/riod-22.webp"],
    powerKw: 22,
    currentType: "AC",
    connectorType: "Type-2",
    ocppCompatible: true,
    smart: true,
    recommendedForBrands: [],
    requestQuoteOnly: true,
    priceInr: 61790,
    installationIncluded: false,
    specs: {
      Input: "415 VAC 3-phase, 32A",
      Output: "22 kW AC",
      Connector: "Type-2",
      Protocol: "OCPP 1.6J",
      Warranty: "3 years",
    },
    faqIds: [],
    seo: {
      title: "RIOD Powerpod 22 kW Commercial EV Charger | ElectricPe",
      description:
        "RIOD Powerpod 22 kW 3-phase commercial EV charger with OCPP. For workplaces, societies, and fleet depots.",
    },
  },
  {
    slug: "teltonika-teltocharge-22kw-4g",
    brand: "teltonika",
    name: "Teltonika TeltoCharge 22 kW + 4G",
    image: "/img/chargers/teltonika-22-4g.webp",
    gallery: ["/img/chargers/teltonika-22-4g.webp"],
    powerKw: 22,
    currentType: "AC",
    connectorType: "Type-2",
    ocppCompatible: true,
    smart: true,
    recommendedForBrands: [],
    requestQuoteOnly: true,
    priceInr: 68480,
    installationIncluded: false,
    specs: {
      Input: "230 VAC 3-phase, 32A",
      Output: "22 kW AC",
      Connector: "Type-2",
      Protocol: "OCPP 1.6J / 2.0.1",
      Connectivity: "Wi-Fi, Ethernet, 4G",
      Warranty: "3 years",
    },
    faqIds: [],
    seo: {
      title: "Teltonika TeltoCharge 22 kW + 4G EV Charger | ElectricPe",
      description:
        "Teltonika TeltoCharge 22 kW with built-in 4G connectivity. Fleet and commercial-grade charging with OCPP 2.0.1 and remote management.",
    },
  },
];

export const getCharger = (slug: string): Charger | undefined =>
  chargers.find((c) => c.slug === slug);
