import type { Store } from "../types";

const standardHours = {
  mon: { open: "10:00", close: "20:00" },
  tue: { open: "10:00", close: "20:00" },
  wed: { open: "10:00", close: "20:00" },
  thu: { open: "10:00", close: "20:00" },
  fri: { open: "10:00", close: "20:00" },
  sat: { open: "10:00", close: "21:00" },
  sun: { open: "10:00", close: "18:00" },
} as const;

export const stores: Store[] = [
  {
    slug: "bengaluru-yeswanthpur",
    name: "ElectricPe Yeswanthpur",
    cityId: "bengaluru",
    state: "Karnataka",
    address: "No 878/2, new no 752.21, Pipeline Road, Yeswanthpur",
    pincode: "560022",
    lat: 13.0289,
    lng: 77.5512,
    phone: "+919632888926",
    whatsapp: "919632888926",
    email: "yeswanthpur@electricpe.com",
    hours: standardHours,
    services: ["sales", "service", "testRides", "charging"],
    brandsAvailable: ["xypro", "jett", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    managerName: "Ramesh K.",
    storeCode: "BLR-YSP",
  },
  {
    slug: "bengaluru-kalyan-nagar",
    name: "ElectricPe Kalyan Nagar",
    cityId: "bengaluru",
    state: "Karnataka",
    address:
      "100 ft RG Road, Annaiya Reddy Layout, Dodda Banaswadi Main Rd, Kalyan Nagar",
    pincode: "560043",
    lat: 13.0283,
    lng: 77.6408,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "BLR-KLN",
  },
  {
    slug: "bengaluru-yelahanka",
    name: "ElectricPe Yelahanka",
    cityId: "bengaluru",
    state: "Karnataka",
    address:
      "Govindappa Complex No 358, 5th phase, 707, Shiva Mandira Road, New Town, Yelahanka",
    pincode: "560064",
    lat: 13.1007,
    lng: 77.5963,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "BLR-YLH",
  },
  {
    slug: "bengaluru-cv-raman-nagar",
    name: "ElectricPe CV Raman Nagar",
    cityId: "bengaluru",
    state: "Karnataka",
    address: "281, Nagavarapalya, C V Raman Nagar",
    pincode: "560093",
    lat: 12.9851,
    lng: 77.671,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides", "charging"],
    brandsAvailable: ["xypro", "jett", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "BLR-CVR",
  },
  {
    slug: "bengaluru-jp-nagar",
    name: "ElectricPe JP Nagar",
    cityId: "bengaluru",
    state: "Karnataka",
    address: "JP Nagar 5th Phase, Bannerghatta Road",
    pincode: "560078",
    lat: 12.9077,
    lng: 77.5857,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "testRides"],
    brandsAvailable: ["xypro", "jett", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "BLR-JPN",
  },
  {
    slug: "delhi-nehru-place",
    name: "ElectricPe Nehru Place",
    cityId: "delhi",
    state: "Delhi",
    address: "Nehru Place District Centre, New Delhi",
    pincode: "110019",
    lat: 28.5489,
    lng: 77.252,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "DEL-NHP",
  },
  {
    slug: "gurugram-sector-14",
    name: "ElectricPe Gurugram Sector 14",
    cityId: "gurugram",
    state: "Haryana",
    address: "Sector 14 Main Market, Gurugram",
    pincode: "122001",
    lat: 28.4669,
    lng: 77.0264,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides", "charging"],
    brandsAvailable: ["xypro", "jett", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "GGM-S14",
  },
  {
    slug: "jaipur-malviya-nagar",
    name: "ElectricPe Malviya Nagar",
    cityId: "jaipur",
    state: "Rajasthan",
    address: "Malviya Nagar, Jaipur",
    pincode: "302017",
    lat: 26.8501,
    lng: 75.8242,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "ep", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "JAI-MLV",
  },
  {
    slug: "hyderabad-madhapur",
    name: "ElectricPe Madhapur",
    cityId: "hyderabad",
    state: "Telangana",
    address: "Madhapur, Hyderabad",
    pincode: "500081",
    lat: 17.4481,
    lng: 78.3915,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides", "charging"],
    brandsAvailable: ["xypro", "jett", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "HYD-MDP",
  },
  {
    slug: "chennai-anna-nagar",
    name: "ElectricPe Anna Nagar",
    cityId: "chennai",
    state: "Tamil Nadu",
    address: "Anna Nagar East, Chennai",
    pincode: "600102",
    lat: 13.0850,
    lng: 80.2101,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "ep"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "CHN-AN",
  },
  {
    slug: "mumbai-andheri",
    name: "ElectricPe Andheri West",
    cityId: "mumbai",
    state: "Maharashtra",
    address: "Andheri West, Mumbai",
    pincode: "400058",
    lat: 19.1136,
    lng: 72.8697,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett", "ep"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "MUM-AND",
  },
  {
    slug: "pune-kothrud",
    name: "ElectricPe Kothrud",
    cityId: "pune",
    state: "Maharashtra",
    address: "Kothrud, Pune",
    pincode: "411038",
    lat: 18.5076,
    lng: 73.8077,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "jett"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "PUN-KTH",
  },
  {
    slug: "ahmedabad-bodakdev",
    name: "ElectricPe Bodakdev",
    cityId: "ahmedabad",
    state: "Gujarat",
    address: "Bodakdev, Ahmedabad",
    pincode: "380054",
    lat: 23.0367,
    lng: 72.5149,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "AMD-BDK",
  },
  {
    slug: "chandigarh-sector-17",
    name: "ElectricPe Chandigarh Sector 17",
    cityId: "chandigarh",
    state: "Chandigarh",
    address: "Sector 17, Chandigarh",
    pincode: "160017",
    lat: 30.7386,
    lng: 76.7836,
    phone: "+919632888926",
    whatsapp: "919632888926",
    hours: standardHours,
    services: ["sales", "service", "testRides"],
    brandsAvailable: ["xypro", "4all"],
    photos: ["/img/home_hero_section_2.webp"],
    storeCode: "CHD-S17",
  },
];

export const getStoresByCity = (citySlug: string): Store[] =>
  stores.filter((s) => s.cityId === citySlug);

export const getStore = (slug: string): Store | undefined =>
  stores.find((s) => s.slug === slug);
